name: Server Create
description: "Supports Creating Servers"
shortDescription: Create A New Server
version: 1.0.0
updateDate: "Sep 28, 2017"
defaultPlaybook: main.yml
author: Runner Team
organization: Runner
organizationUrl: https://runner.ctl.io

fields:

  - name: server
    displayName: Server
    type: server
    serverType:
      default: standard
    operatingSystem:
      default: WIN2016DTC-64
    serverName:
      default: TEST
    serverDescription:
      default: TEST
    cpu:
      min: 1
      max: 16
      default: 2
    memory:
      min: 1
      max: 128
      default: 4
    count:
      min: 1
      max: 100
      default: 1
    required: true

tags:
  - server
  - iaas
  - vm
  - bare-metal
